Neos:
  Neos:
    userInterface:
      requireJsPathMapping:
        'Neos.GoogleAnalytics/Inspector/Editors': 'resource://Neos.GoogleAnalytics/Public/Scripts/Inspector/Editors'
      translation:
        autoInclude:
          'Neos.GoogleAnalytics': ['NodeTypes/*']

    modules:
      administration:
        submodules:
          googleAnalytics:
            label: 'Analytics'
            controller: 'Neos\GoogleAnalytics\Controller\ConfigurationController'
            description: 'Google Analytics configuration'
            icon: 'icon-bar-chart icon-line-chart'
            privilegeTarget: 'Neos.GoogleAnalytics:Module.Administration.Configuration'

    fusion:
      autoInclude:
        'Neos.GoogleAnalytics': true

  GoogleAnalytics:
    enableTracking: true

    stats:
      uniquePageviewsPerDay:
        metrics: 'ga:uniquePageviews'
        dimensions: 'ga:date'
      basic:
        metrics: 'ga:pageviews,ga:uniquePageviews,ga:users'
      uniquePageviewsByUserType:
        metrics: 'ga:uniquePageviews'
        dimensions: 'ga:userType'
      uniquePageviewsByDeviceCategory:
        metrics: 'ga:uniquePageviews'
        dimensions: 'ga:deviceCategory'

    # Site specific settings
    sites: []
      ## All site specific settings are indexed by site node name
      #
      # neosdemo:
      #   trackingId: 'UA-XXXXX-YY'
      #   profileId: '12345678'
